services:
  web:
    container_name: web
    build: web
    ports:
      - '5000:5000'
    volumes:
      - ./web/:/web/
      - /web/node_modules/
  app:
    container_name: app
    build: app
    ports:
      - '8000:8000'
    volumes:
      - ./app/:/app/
      - /app/instance/
